# Generated by Django 5.0.3 on 2024-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='details',
            field=models.TextField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(blank=True, default='app.logomakr.com/3EC6KR', max_length=2000, null=True),
        ),
    ]
