# Generated by Django 5.0.3 on 2024-04-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_details_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, default='app.logomakr.com/3EC6KR', max_length=6000, null=True),
        ),
    ]
