# Generated by Django 5.0.3 on 2024-04-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_image_blog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_url',
        ),
    ]
